In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop('User ID',axis=1)

In [7]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [8]:
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]
dependent=dataset[['Purchased']]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [21]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy','log_loss'],
            'max_features':['auto','sqrt','log2'],
            'splitter':['best','random']}

grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=2,cv=5,n_jobs=1,scoring='f1_weighted')
grid=grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ...criterion=gini, max_features=auto, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=auto, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=auto, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=auto, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=auto, splitter=best; total time=   0.0s
[CV] END .criterion=gini, max_features=auto, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=auto, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=auto, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=auto, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=auto, splitter=random; total time=   0.0s
[CV] END ...criterion=gini, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END .criterion=gini, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END ...criterion=gini, max_features=log2, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=log2, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=log2, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=log2, splitter=best; total time=   0.0s
[CV] END ...criterion=gini, max_features=log2, splitter=best; total time=   0.0s
[CV] END .criterion=gini, max_features=log2, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=log2, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=log2, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=log2, splitter=random; total time=   0.0s
[CV] END .criterion=gini, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=entropy, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=auto, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=sqrt, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=best; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=random; total time=   0.0s
[CV] END criterion=log_loss, max_features=log2, splitter=random; total time=   0.0s

D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
D:\Anaconda3\envs\Kathir\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.82440526 0.82726584 0.84256713 0.8396877
        nan        nan 0.84131654 0.8630541  0.84187932 0.83392102
        nan        nan 0.84911209 0.83000356 0.83774008 0.81156517]
  warnings.warn(

In [22]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
grid_pred=grid.predict(x_test)

In [23]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000920,0.000814,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.000757,0.000513,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.001781,0.001476,0.008648,0.002190,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.852966,0.785714,0.806153,0.804432,0.872761,0.824405,0.032812,11
3,0.003291,0.003066,0.004172,0.004356,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.779449,0.874254,0.789152,0.839990,0.853485,0.827266,0.036868,10
4,0.000000,0.000000,0.005536,0.004130,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.799537,0.823129,0.807155,0.910254,0.872761,0.842567,0.042371,3
5,0.000000,0.000000,0.003134,0.006267,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.858503,0.857143,0.823129,0.752005,0.907658,0.839688,0.051461,6
6,0.000000,0.000000,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.000676,0.001351,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.000000,0.000000,0.009392,0.002086,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.833024,0.819142,0.787755,0.855556,0.911105,0.841317,0.041237,5
9,0.000329,0.000658,0.007306,0.002168,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.795918,0.857143,0.841398,0.929144,0.891667,0.863054,0.045161,1
10,0.003128,0.006255,0.004789,0.006005,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.855314,0.875644,0.823129,0.804432,0.850877,0.841879,0.025121,4
11,0.006250,0.007655,0.003125,0.006250,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.819142,0.857143,0.823129,0.836407,0.833784,0.833921,0.013269,8
12,0.000000,0.000000,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.000000,0.000000,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.002463,0.003247,0.008858,0.006298,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.874254,0.857143,0.802399,0.841045,0.870721,0.849112,0.026118,2
15,0.001413,0.002826,0.008640,0.003566,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.829361,0.840114,0.821429,0.750000,0.909115,0.830004,0.050666,9
16,0.000000,0.000000,0.007778,0.004967,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.891485,0.840114,0.750000,0.910254,0.796847,0.837740,0.059200,7
17,0.000000,0.000000,0.006250,0.007655,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.782971,0.787755,0.787755,0.859355,0.839990,0.811565,0.031759,12

In [24]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)

In [25]:
cm

array([[70,  9],
       [ 9, 32]])

In [26]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        79
           1       0.78      0.78      0.78        41

    accuracy                           0.85       120
   macro avg       0.83      0.83      0.83       120
weighted avg       0.85      0.85      0.85       120

In [27]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_pred,average='weighted')
print('The f1 macro value from best parameters{}:'.format(grid.best_params_),f1_macro)

The f1 macro value from best parameters{'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'}: 0.85

In [28]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.8332818771225687)